export interface User {
  id: string;
  email: string;
  name: string;
  provider: 'email' | 'google' | 'apple' | 'kakao';
  profileImage?: string;
  createdAt: string;
  updatedAt: string;
}

export interface AuthResponse {
  accessToken: string;
  refreshToken: string;
  user: User;
}

export interface Trip {
  id: string;
  userId: string;
  destinationCountry: string;
  destinationRegion: string;
  startDate: string;
  endDate: string;
  status: 'planning' | 'ongoing' | 'completed';
  autoGenerated: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface ItineraryItem {
  id: string;
  tripId: string;
  dayNumber: number;
  timeSlot: string;
  title: string;
  description: string;
  locationName: string;
  locationLat?: number;
  locationLng?: number;
  category: string;
  completed: boolean;
  isEditable: boolean;
  createdAt: string;
  updatedAt: string;
}
