// AUTO-GENERATED by scripts/generate-blog-manifest.py — DO NOT EDIT BY HAND.
// Run `python3 scripts/generate-blog-manifest.py` after adding/removing
// blog or guide pages. `validate-content.py` fails CI if this is stale.

export type ContentLang = 'ko' | 'en' | 'ja';

export interface ContentEntry {
  /** Canonical (Korean) slug, e.g. 'ai-budget-planning'. */
  slug: string;
  /** Available language variants mapped to their lastmod date (YYYY-MM-DD). */
  langs: Partial<Record<ContentLang, string>>;
}

export const BLOG_ENTRIES: ContentEntry[] = [
  { slug: "accommodation-choosing-guide", langs: { en: "2026-07-25", ja: "2026-07-25", ko: "2026-07-25" } },
  { slug: "accommodation-saving-tips", langs: { en: "2026-07-10", ja: "2026-07-10", ko: "2026-07-10" } },
  { slug: "ai-budget-planning", langs: { en: "2026-07-10", ja: "2026-07-10", ko: "2026-07-10" } },
  { slug: "ai-itinerary-customizing", langs: { en: "2026-07-10", ja: "2026-07-10", ko: "2026-07-10" } },
  { slug: "ai-restaurant-recommendation", langs: { en: "2026-07-10", ja: "2026-07-10", ko: "2026-07-10" } },
  { slug: "ai-travel-planning-tips", langs: { ko: "2026-07-10" } },
  { slug: "airline-miles-guide", langs: { en: "2026-07-10", ja: "2026-07-10", ko: "2026-07-10" } },
  { slug: "airport-time-saving-tips", langs: { ko: "2026-07-10" } },
  { slug: "bangkok-4day-course", langs: { en: "2026-07-10", ja: "2026-07-10", ko: "2026-07-10" } },
  { slug: "budget-travel-guide", langs: { ko: "2026-07-10" } },
  { slug: "carry-on-essentials-guide", langs: { en: "2026-07-10", ja: "2026-07-10", ko: "2026-07-10" } },
  { slug: "cheap-flight-booking-guide", langs: { en: "2026-07-10", ja: "2026-07-10", ko: "2026-07-10" } },
  { slug: "currency-exchange-guide", langs: { ko: "2026-07-10" } },
  { slug: "currency-exchange-timing", langs: { en: "2026-07-10", ja: "2026-07-10", ko: "2026-07-10" } },
  { slug: "danang-hoian-course", langs: { en: "2026-07-10", ja: "2026-07-10", ko: "2026-07-10" } },
  { slug: "europe-culture-differences", langs: { ko: "2026-07-10" } },
  { slug: "family-travel-planning", langs: { ko: "2026-07-10" } },
  { slug: "first-solo-travel", langs: { ko: "2026-07-10" } },
  { slug: "group-trip-expense-split", langs: { en: "2026-07-25", ja: "2026-07-25", ko: "2026-07-25" } },
  { slug: "group-trip-planning", langs: { en: "2026-07-25", ja: "2026-07-25", ko: "2026-07-25" } },
  { slug: "japan-transport-pass-guide", langs: { ko: "2026-07-10" } },
  { slug: "jetlag-management-guide", langs: { en: "2026-07-10", ja: "2026-07-10", ko: "2026-07-10" } },
  { slug: "local-experience-tips", langs: { en: "2026-07-10", ja: "2026-07-10", ko: "2026-07-10" } },
  { slug: "local-food-guide", langs: { en: "2026-07-25", ja: "2026-07-25", ko: "2026-07-25" } },
  { slug: "long-flight-comfort-tips", langs: { en: "2026-07-10", ja: "2026-07-10", ko: "2026-07-10" } },
  { slug: "long-term-travel-guide", langs: { ko: "2026-07-10" } },
  { slug: "osaka-kyoto-course", langs: { en: "2026-07-10", ja: "2026-07-10", ko: "2026-07-10" } },
  { slug: "packing-checklist", langs: { ko: "2026-07-10" } },
  { slug: "passport-renewal-guide", langs: { en: "2026-07-10", ja: "2026-07-10", ko: "2026-07-10" } },
  { slug: "pet-travel-guide", langs: { en: "2026-07-10", ja: "2026-07-10", ko: "2026-07-10" } },
  { slug: "roaming-vs-esim-guide", langs: { en: "2026-07-10", ja: "2026-07-10", ko: "2026-07-10" } },
  { slug: "seasonal-best-destinations", langs: { en: "2026-07-10", ja: "2026-07-10", ko: "2026-07-10" } },
  { slug: "senior-travel-guide", langs: { en: "2026-07-10", ja: "2026-07-10", ko: "2026-07-10" } },
  { slug: "smartphone-travel-photography", langs: { ko: "2026-07-10" } },
  { slug: "solo-female-travel-safety", langs: { en: "2026-07-10", ja: "2026-07-10", ko: "2026-07-10" } },
  { slug: "southeast-asia-rainy-season", langs: { ko: "2026-07-10" } },
  { slug: "sustainable-travel-guide", langs: { en: "2026-07-10", ja: "2026-07-10", ko: "2026-07-10" } },
  { slug: "taipei-3day-course", langs: { en: "2026-07-10", ja: "2026-07-10", ko: "2026-07-10" } },
  { slug: "tokyo-3day-course", langs: { en: "2026-07-10", ja: "2026-07-10", ko: "2026-07-10" } },
  { slug: "travel-app-recommendations", langs: { en: "2026-07-10", ja: "2026-07-10", ko: "2026-07-10" } },
  { slug: "travel-emergency-guide", langs: { en: "2026-07-10", ja: "2026-07-10", ko: "2026-07-10" } },
  { slug: "travel-etiquette-guide", langs: { en: "2026-07-25", ja: "2026-07-25", ko: "2026-07-25" } },
  { slug: "travel-insurance-guide", langs: { ko: "2026-07-10" } },
  { slug: "travel-internet-guide", langs: { ko: "2026-07-10" } },
  { slug: "travel-journal-tips", langs: { ko: "2026-07-10" } },
  { slug: "travel-photography-spots", langs: { en: "2026-07-10", ja: "2026-07-10", ko: "2026-07-10" } },
  { slug: "travel-safety-guide", langs: { en: "2026-07-25", ja: "2026-07-25", ko: "2026-07-25" } },
  { slug: "travel-vaccination-guide", langs: { en: "2026-07-10", ja: "2026-07-10", ko: "2026-07-10" } },
  { slug: "trip-planning-checklist", langs: { en: "2026-07-25", ja: "2026-07-25", ko: "2026-07-25" } },
  { slug: "visa-guide-for-travelers", langs: { en: "2026-07-10", ja: "2026-07-10", ko: "2026-07-10" } },
  { slug: "workation-guide", langs: { en: "2026-07-10", ja: "2026-07-10", ko: "2026-07-10" } },
];

export const GUIDE_ENTRIES: ContentEntry[] = [
  { slug: "amsterdam", langs: { ko: "2026-04-26" } },
  { slug: "bali", langs: { ko: "2026-04-26" } },
  { slug: "bangkok", langs: { en: "2026-04-26", ko: "2026-04-26" } },
  { slug: "barcelona", langs: { ko: "2026-04-26" } },
  { slug: "dubai", langs: { ko: "2026-04-26" } },
  { slug: "hawaii", langs: { ko: "2026-04-26" } },
  { slug: "ho-chi-minh", langs: { ko: "2026-04-26" } },
  { slug: "istanbul", langs: { ko: "2026-04-26" } },
  { slug: "kuala-lumpur", langs: { ko: "2026-04-26" } },
  { slug: "kyoto", langs: { ko: "2026-04-26" } },
  { slug: "london", langs: { ko: "2026-04-26" } },
  { slug: "new-york", langs: { ko: "2026-04-26" } },
  { slug: "osaka", langs: { en: "2026-04-26", ko: "2026-04-26" } },
  { slug: "paris", langs: { en: "2026-04-26", ko: "2026-04-26" } },
  { slug: "prague", langs: { ko: "2026-04-26" } },
  { slug: "rome", langs: { ko: "2026-04-26" } },
  { slug: "seoul", langs: { en: "2026-03-14", ko: "2026-04-26" } },
  { slug: "singapore", langs: { ko: "2026-04-26" } },
  { slug: "sydney", langs: { ko: "2026-04-26" } },
  { slug: "tokyo", langs: { en: "2026-04-26", ko: "2026-04-26" } },
];
