#!/usr/bin/env python3
"""Generate a static sitemap manifest from the blog/guides HTML files.

Why this exists
---------------
The sitemap used to hardcode every blog/guide URL inside
``backend/src/app.controller.ts``. Adding a post meant editing that array by
hand, and forgetting to do so left the post out of the sitemap entirely — a
"ghost page" that exists on disk but is invisible to search engines.

This script makes the *file system the source of truth*. It scans
``frontend/public/blog`` and ``frontend/public/guides``, groups files by their
canonical slug and language (from the ``-en`` / ``-ja`` filename suffix), reads
the ``dateModified`` from each page's JSON-LD for an accurate ``<lastmod>``, and
emits a TypeScript manifest that the backend imports.

Because the manifest is a committed ``.ts`` file that lives next to the HTML in
the same repo, the two can never drift: a CI check (see ``validate-content.py``)
fails the build if a published page is missing from the manifest.

Language rule
-------------
- ``{slug}.html``      -> Korean (ko, the x-default / canonical)
- ``{slug}-en.html``   -> English (en)
- ``{slug}-ja.html``   -> Japanese (ja)
- ``index*`` files are section landing pages, handled separately, not posts.

Usage
-----
    python3 scripts/generate-blog-manifest.py            # write manifest
    python3 scripts/generate-blog-manifest.py --check    # CI: fail if stale
"""

from __future__ import annotations

import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
BLOG_DIR = REPO_ROOT / "frontend" / "public" / "blog"
GUIDES_DIR = REPO_ROOT / "frontend" / "public" / "guides"
OUTPUT = REPO_ROOT / "backend" / "src" / "marketing" / "blog-manifest.ts"

# Priority / changefreq mirror the values the hand-written sitemap used, so this
# change is a pure refactor of *how* the URLs are produced, not their metadata.
SECTION_META = {
    "blog": {"post_priority": "0.75", "changefreq": "monthly"},
    "guides": {"post_priority": "0.85", "changefreq": "monthly"},
}

LANG_SUFFIX = {"-en": "en", "-ja": "ja"}
DATE_MODIFIED_RE = re.compile(r'"dateModified"\s*:\s*"(\d{4}-\d{2}-\d{2})"')


@dataclass
class Entry:
    """One logical page (a slug) with all its language variants."""

    slug: str
    # lang -> lastmod date string (YYYY-MM-DD); ko is always present.
    langs: dict[str, str] = field(default_factory=dict)


def _canonical_slug_and_lang(stem: str) -> tuple[str, str]:
    """Split a filename stem into (canonical_slug, lang).

    ``ai-budget-planning-en`` -> ("ai-budget-planning", "en")
    ``ai-budget-planning``    -> ("ai-budget-planning", "ko")
    """
    for suffix, lang in LANG_SUFFIX.items():
        if stem.endswith(suffix):
            return stem[: -len(suffix)], lang
    return stem, "ko"


def _read_lastmod(path: Path) -> str | None:
    try:
        text = path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return None
    match = DATE_MODIFIED_RE.search(text)
    return match.group(1) if match else None


def scan_section(directory: Path) -> list[Entry]:
    """Return entries for one content section, sorted by slug."""
    entries: dict[str, Entry] = {}
    for path in sorted(directory.glob("*.html")):
        stem = path.stem
        # Section landing pages (index, index-en, ...) are not posts.
        if stem == "index" or stem.startswith("index-"):
            continue
        slug, lang = _canonical_slug_and_lang(stem)
        lastmod = _read_lastmod(path)
        entry = entries.setdefault(slug, Entry(slug=slug))
        if lastmod:
            entry.langs[lang] = lastmod
        else:
            # Keep the language even without a date; the renderer falls back to
            # the build date rather than dropping the URL.
            entry.langs.setdefault(lang, "")
    # A page with no Korean variant would be an anomaly; keep it but it will
    # still render with whatever langs it has.
    return [entries[s] for s in sorted(entries)]


def render_ts(blog: list[Entry], guides: list[Entry]) -> str:
    def entries_literal(entries: list[Entry]) -> str:
        lines = []
        for e in entries:
            langs = ", ".join(
                f"{lang}: {date!r}".replace("'", '"')
                for lang, date in sorted(e.langs.items())
            )
            lines.append(f'  {{ slug: "{e.slug}", langs: {{ {langs} }} }},')
        return "\n".join(lines)

    return (
        "// AUTO-GENERATED by scripts/generate-blog-manifest.py — DO NOT EDIT BY HAND.\n"
        "// Run `python3 scripts/generate-blog-manifest.py` after adding/removing\n"
        "// blog or guide pages. `validate-content.py` fails CI if this is stale.\n"
        "\n"
        "export type ContentLang = 'ko' | 'en' | 'ja';\n"
        "\n"
        "export interface ContentEntry {\n"
        "  /** Canonical (Korean) slug, e.g. 'ai-budget-planning'. */\n"
        "  slug: string;\n"
        "  /** Available language variants mapped to their lastmod date (YYYY-MM-DD). */\n"
        "  langs: Partial<Record<ContentLang, string>>;\n"
        "}\n"
        "\n"
        f"export const BLOG_ENTRIES: ContentEntry[] = [\n{entries_literal(blog)}\n];\n"
        "\n"
        f"export const GUIDE_ENTRIES: ContentEntry[] = [\n{entries_literal(guides)}\n];\n"
    )


def main() -> int:
    check_only = "--check" in sys.argv

    if not BLOG_DIR.is_dir() or not GUIDES_DIR.is_dir():
        print(f"ERROR: content dirs not found under {REPO_ROOT}", file=sys.stderr)
        return 2

    blog = scan_section(BLOG_DIR)
    guides = scan_section(GUIDES_DIR)
    rendered = render_ts(blog, guides)

    blog_variants = sum(len(e.langs) for e in blog)
    guide_variants = sum(len(e.langs) for e in guides)

    if check_only:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != rendered:
            print(
                "ERROR: blog-manifest.ts is stale. Run "
                "`python3 scripts/generate-blog-manifest.py` and commit.",
                file=sys.stderr,
            )
            return 1
        print(
            f"OK: manifest up to date "
            f"(blog: {len(blog)} slugs / {blog_variants} variants, "
            f"guides: {len(guides)} slugs / {guide_variants} variants)"
        )
        return 0

    OUTPUT.write_text(rendered, encoding="utf-8")
    print(
        f"Wrote {OUTPUT.relative_to(REPO_ROOT)}\n"
        f"  blog:   {len(blog)} slugs, {blog_variants} language variants\n"
        f"  guides: {len(guides)} slugs, {guide_variants} language variants"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
